apiVersion: v1
kind: Service
metadata:
  name: nfs-server-service
spec:
  selector:
    app: nfs-server
  ports:
    - name: tcp-2049
      port: 2049
      protocol: TCP
    - name: udp-111
      port: 111
      protocol: UDP
  type: NodePort # Exposes the service outside the cluster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-server
  template:
    metadata:
      labels:
        app: nfs-server
    spec:
      containers:
      - name: nfs-server
        image: itsthenetwork/nfs-server-alpine:latest
        env:
        - name: SHARED_DIRECTORY
          value: "/exports"
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true # Required to run an NFS server in a container
        volumeMounts:
        - mountPath: /exports
          name: nfs-storage
      volumes:
      - name: nfs-storage
        hostPath:
          path: /export/nfs # Uses the directory on the underlying EC2 instance
          type: DirectoryOrCreate